/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'role' : string,
}
export interface TimesheetEntry {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'hoursWorked' : number,
  'site' : string,
  'clockOut' : string,
  'clockIn' : string,
  'employeeId' : bigint,
  'notes' : string,
}
export interface _SERVICE {
  'addEmployee' : ActorMethod<[string, string], bigint>,
  'addEntry' : ActorMethod<
    [bigint, string, string, string, string, string, number],
    bigint
  >,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getActiveEmployees' : ActorMethod<[], Array<Employee>>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getEntries' : ActorMethod<[], Array<TimesheetEntry>>,
  'getEntriesByEmployee' : ActorMethod<[bigint], Array<TimesheetEntry>>,
  'removeEmployee' : ActorMethod<[bigint], undefined>,
  'updateEmployee' : ActorMethod<[bigint, string, string, boolean], undefined>,
  'updateEntry' : ActorMethod<
    [bigint, bigint, string, string, string, string, string, number, string],
    undefined
  >,
  'updateEntryStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];