/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const TimesheetEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'hoursWorked' : IDL.Float64,
  'site' : IDL.Text,
  'clockOut' : IDL.Text,
  'clockIn' : IDL.Text,
  'employeeId' : IDL.Nat,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(TimesheetEntry)], ['query']),
  'getEntriesByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimesheetEntry)],
      ['query'],
    ),
  'removeEmployee' : IDL.Func([IDL.Nat], [], []),
  'updateEmployee' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateEntryStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const TimesheetEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'hoursWorked' : IDL.Float64,
    'site' : IDL.Text,
    'clockOut' : IDL.Text,
    'clockIn' : IDL.Text,
    'employeeId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(TimesheetEntry)], ['query']),
    'getEntriesByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimesheetEntry)],
        ['query'],
      ),
    'removeEmployee' : IDL.Func([IDL.Nat], [], []),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateEntryStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };